name: Flutter Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # See https://github.com/subosito/flutter-action 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test
    - run: flutter build web
    - run: flutter build appbundle
